-- Migration: 20260928000006_seed_catalog.sql
-- Description: Seed initial categories and catalog products for NEW Supabase project

-- 1. Insert Categories
insert into public.categories (name, slug, display_order, is_active)
values
  ('Flowers', 'flowers', 1, true),
  ('Bouquets', 'bouquets', 2, true),
  ('Gifts', 'gifts', 3, true),
  ('Bags', 'bags', 4, true),
  ('Home Décor', 'decor', 5, true),
  ('Gift Boxes', 'giftboxes', 6, true),
  ('Custom', 'custom', 7, true)
on conflict (slug) do update set
  name = excluded.name,
  display_order = excluded.display_order;

-- 2. Insert Products

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-FL-001',
  'Evermore Rose',
  'tpb-fl-001',
  'flowers',
  34900,
  null,
  'A handmade crochet rose designed to last far beyond the day it is gifted.',
  'The Evermore Rose is our signature single bloom — a handmade crochet rose shaped stitch by stitch to capture the softness of a real petal. Designed to sit on a desk, a shelf, or a bedside table, it is a quiet reminder of a moment worth keeping.',
  15,
  true,
  true,
  true,
  true,
  true,
  '3–5 days',
  '',
  ARRAY['https://images.pexels.com/photos/18809860/pexels-photo-18809860.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/7185718/pexels-photo-7185718.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/31583953/pexels-photo-31583953.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Red', 'Pink', 'White', 'Lavender', 'Yellow', 'Custom']::text[],
  ARRAY['Birthday', 'Anniversary', 'Friendship', 'Gifting']::text[],
  ARRAY['Partner', 'Friend', 'Mother']::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-FL-002',
  'Golden Sun',
  'tpb-fl-002',
  'flowers',
  34900,
  null,
  'A warm sunflower bloom that brings a little light to any corner.',
  'The Golden Sun is a cheerful crochet sunflower with warm golden petals and a textured centre. It is the kind of bloom that makes a room feel a little brighter — and a gift feel a little more thoughtful.',
  15,
  true,
  true,
  false,
  false,
  true,
  '3–5 days',
  '',
  ARRAY['https://images.pexels.com/photos/36007970/pexels-photo-36007970.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/32501693/pexels-photo-32501693.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Golden Yellow', 'Mustard', 'Cream', 'Custom']::text[],
  ARRAY['Birthday', 'Friendship', 'Just Because']::text[],
  ARRAY['Friend', 'Sibling']::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-FL-003',
  'Daisy Daydream',
  'tpb-fl-003',
  'flowers',
  29900,
  null,
  'Simple, sweet, and made to sit quietly among your favourite things.',
  'The Daisy Daydream is a delicate crochet daisy with soft white petals and a warm centre. Understated and gentle, it is the bloom for someone who appreciates the little things.',
  15,
  true,
  false,
  false,
  false,
  true,
  '3–5 days',
  '',
  ARRAY['https://images.pexels.com/photos/5775875/pexels-photo-5775875.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/32914223/pexels-photo-32914223.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['White', 'Pink', 'Yellow', 'Custom']::text[],
  ARRAY['Friendship', 'Just Because', 'Birthday']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-FL-004',
  'Petal Whisper Tulip',
  'tpb-fl-004',
  'flowers',
  34900,
  null,
  'A graceful crochet tulip with a slender stem and soft cupped petals.',
  'The Petal Whisper Tulip captures the quiet elegance of a single tulip in yarn. Its slender stem and cupped petals make it a beautiful standalone piece or a thoughtful addition to a larger bouquet.',
  15,
  true,
  true,
  false,
  false,
  true,
  '3–5 days',
  '',
  ARRAY['https://images.pexels.com/photos/24361048/pexels-photo-24361048.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/31104018/pexels-photo-31104018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Pink', 'White', 'Lavender', 'Yellow', 'Custom']::text[],
  ARRAY['Birthday', 'Anniversary', 'Mother''s Day']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-FL-005',
  'Premium Rose',
  'tpb-fl-005',
  'flowers',
  39900,
  null,
  'A larger, fuller crochet rose with layered petals and a premium finish.',
  'The Premium Rose is our most refined single bloom — larger, with more layered petals and a richer texture. It is the rose for moments that deserve something a little more.',
  15,
  true,
  true,
  false,
  true,
  true,
  '4–6 days',
  '',
  ARRAY['https://images.pexels.com/photos/17143519/pexels-photo-17143519.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/7185718/pexels-photo-7185718.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Red', 'Pink', 'White', 'Lavender', 'Peach', 'Custom']::text[],
  ARRAY['Anniversary', 'Valentine''s Day', 'Mother''s Day']::text[],
  ARRAY['Partner', 'Mother']::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BQ-001',
  'Little Bloom',
  'tpb-bq-001',
  'bouquets',
  49900,
  null,
  'One handmade bloom, wrapped and ready to make someone smile.',
  'The Little Bloom is our simplest bouquet — a single crochet flower, wrapped with care. It is the perfect little gesture for someone who deserves a moment of thought.',
  15,
  true,
  false,
  false,
  false,
  true,
  '3–5 days',
  '1 flower',
  ARRAY['https://images.pexels.com/photos/17864125/pexels-photo-17864125.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/17864123/pexels-photo-17864123.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Red', 'Pink', 'White', 'Lavender', 'Yellow', 'Custom']::text[],
  ARRAY['Just Because', 'Friendship', 'Birthday']::text[],
  ARRAY[]::text[],
  ARRAY['Handmade crochet flower', 'Premium wrapping', 'Ribbon', 'Gift-ready presentation']::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BQ-002',
  'Bloom Duo',
  'tpb-bq-002',
  'bouquets',
  69900,
  null,
  'Two complementary blooms brought together in a small, thoughtful pairing.',
  'The Bloom Duo pairs two complementary crochet flowers — a rose and a tulip, a daisy and a sunflower — wrapped together as a small story. It is the bouquet for a friendship, a thank-you, or a quiet celebration.',
  15,
  true,
  true,
  false,
  false,
  true,
  '4–6 days',
  '2 flowers',
  ARRAY['https://images.pexels.com/photos/20269074/pexels-photo-20269074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/32280850/pexels-photo-32280850.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Custom mix available']::text[],
  ARRAY['Friendship', 'Birthday', 'Anniversary']::text[],
  ARRAY[]::text[],
  ARRAY['2 handmade crochet flowers', 'Premium wrapping', 'Ribbon', 'Gift-ready presentation']::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BQ-003',
  'Trio of Petals',
  'tpb-bq-003',
  'bouquets',
  89900,
  null,
  'Three handmade blooms, brought together into one little story.',
  'The Trio of Petals is our most-loved bouquet. Three crochet flowers — each chosen to complement the others — wrapped together in premium packaging. It is the bouquet that turns a gift into a moment.',
  15,
  true,
  true,
  true,
  true,
  true,
  '4–6 days',
  '3 flowers',
  ARRAY['https://images.pexels.com/photos/20269075/pexels-photo-20269075.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/29753251/pexels-photo-29753251.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/28450065/pexels-photo-28450065.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Custom mix available']::text[],
  ARRAY['Birthday', 'Anniversary', 'Valentine''s Day', 'Mother''s Day']::text[],
  ARRAY[]::text[],
  ARRAY['3 handmade crochet flowers', 'Premium wrapping', 'Ribbon', 'Gift-ready presentation']::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BQ-004',
  'Petal Story',
  'tpb-bq-004',
  'bouquets',
  129900,
  null,
  'Five blooms arranged into a fuller, more expressive bouquet.',
  'The Petal Story is a bouquet with more to say. Five crochet flowers in a considered arrangement, wrapped in premium packaging with a ribbon finish. It is the bouquet for anniversaries, milestones, and moments that deserve more than a single bloom.',
  15,
  true,
  true,
  false,
  false,
  true,
  '5–7 days',
  '5 flowers',
  ARRAY['https://images.pexels.com/photos/29753249/pexels-photo-29753249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/20269075/pexels-photo-20269075.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Custom mix available']::text[],
  ARRAY['Anniversary', 'Mother''s Day', 'Birthday']::text[],
  ARRAY[]::text[],
  ARRAY['5 handmade crochet flowers', 'Premium wrapping', 'Ribbon', 'Gift-ready presentation']::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BQ-005',
  'Garden in Bloom',
  'tpb-bq-005',
  'bouquets',
  159900,
  null,
  'Seven flowers gathered into a rich, layered crochet bouquet.',
  'The Garden in Bloom is a generous arrangement — seven crochet flowers in a mix of roses, tulips, and daisies, wrapped and finished with a premium ribbon. It is the bouquet that feels like a whole garden in your hands.',
  15,
  true,
  true,
  false,
  false,
  true,
  '5–7 days',
  '7 flowers',
  ARRAY['https://images.pexels.com/photos/29753249/pexels-photo-29753249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/39412616/pexels-photo-39412616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Custom mix available']::text[],
  ARRAY['Anniversary', 'Mother''s Day', 'Wedding', 'Festivals']::text[],
  ARRAY[]::text[],
  ARRAY['7 handmade crochet flowers', 'Premium wrapping', 'Ribbon', 'Gift-ready presentation']::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BQ-006',
  'Forever Garden',
  'tpb-bq-006',
  'bouquets',
  199900,
  null,
  'Nine blooms — our largest standard bouquet, made to be unforgettable.',
  'The Forever Garden is our most generous standard bouquet. Nine crochet flowers arranged into a rich, full composition, wrapped in premium packaging and finished with a ribbon. It is the bouquet for once-in-a-lifetime moments.',
  15,
  true,
  true,
  false,
  true,
  true,
  '6–8 days',
  '9 flowers',
  ARRAY['https://images.pexels.com/photos/39412616/pexels-photo-39412616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/29753249/pexels-photo-29753249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Custom mix available']::text[],
  ARRAY['Anniversary', 'Wedding', 'Mother''s Day']::text[],
  ARRAY[]::text[],
  ARRAY['9 handmade crochet flowers', 'Premium wrapping', 'Ribbon', 'Gift-ready presentation']::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BQ-007',
  'Premium Mixed Bouquet',
  'tpb-bq-007',
  'bouquets',
  149900,
  null,
  'A curated mix of flower types and colours for a one-of-a-kind arrangement.',
  'The Premium Mixed Bouquet is a curated blend of different flower types — roses, tulips, daisies, and sunflowers — chosen to create a rich, textured arrangement. No two are exactly alike.',
  15,
  true,
  true,
  false,
  false,
  true,
  '5–7 days',
  '5–7 flowers',
  ARRAY['https://images.pexels.com/photos/29753249/pexels-photo-29753249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/20269074/pexels-photo-20269074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Curated mix']::text[],
  ARRAY['Birthday', 'Anniversary', 'Festivals']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BQ-008',
  'Large Premium Bouquet',
  'tpb-bq-008',
  'bouquets',
  249900,
  null,
  'Our grandest bouquet — a lush, abundant arrangement for the most special occasions.',
  'The Large Premium Bouquet is our most abundant creation — a generous arrangement of 10+ crochet flowers in a rich, layered composition. Made for weddings, milestone anniversaries, and moments that deserve the fullest expression.',
  15,
  true,
  true,
  false,
  false,
  true,
  '7–10 days',
  '10+ flowers',
  ARRAY['https://images.pexels.com/photos/39412616/pexels-photo-39412616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/29753249/pexels-photo-29753249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Custom mix available']::text[],
  ARRAY['Wedding', 'Anniversary', 'Corporate Gifting']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-KR-001',
  'Pocket Bloom Keyring',
  'tpb-kr-001',
  'gifts',
  19900,
  null,
  'A tiny crochet bloom you can carry everywhere.',
  'The Pocket Bloom Keyring is a miniature crochet flower attached to a sturdy keyring. It is the smallest way to carry a little beauty with you — and a lovely little gift for someone who deserves a small surprise.',
  15,
  true,
  false,
  true,
  false,
  true,
  '2–4 days',
  '',
  ARRAY['https://images.pexels.com/photos/37129474/pexels-photo-37129474.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/38634277/pexels-photo-38634277.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Red', 'Pink', 'White', 'Lavender', 'Yellow']::text[],
  ARRAY['Just Because', 'Friendship', 'Return Gift']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-KR-002',
  'Premium Custom Keyring',
  'tpb-kr-002',
  'gifts',
  24900,
  null,
  'A custom-colour crochet keyring with a premium finish.',
  'The Premium Custom Keyring lets you choose the colour, the flower type, and the accent. It is a small, personal gift made to order — and a favourite for return gifts and party favours.',
  15,
  true,
  true,
  false,
  false,
  true,
  '3–5 days',
  '',
  ARRAY['https://images.pexels.com/photos/38634277/pexels-photo-38634277.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/37129474/pexels-photo-37129474.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Custom']::text[],
  ARRAY['Return Gift', 'Friendship', 'Just Because']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-KR-003',
  'Flower Bookmark',
  'tpb-kr-003',
  'gifts',
  19900,
  null,
  'A delicate crochet flower bookmark for the readers you love.',
  'The Flower Bookmark is a slim crochet flower attached to a bookmark stem — a gentle, literary gift for the readers in your life. It sits beautifully between pages and lasts far longer than a real petal.',
  15,
  true,
  true,
  false,
  false,
  true,
  '2–4 days',
  '',
  ARRAY['https://images.pexels.com/photos/36595917/pexels-photo-36595917.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/34352098/pexels-photo-34352098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Pink', 'White', 'Lavender', 'Yellow', 'Custom']::text[],
  ARRAY['Friendship', 'Just Because', 'Birthday']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-HD-001',
  'Mini Flower Pot',
  'tpb-hd-001',
  'decor',
  49900,
  null,
  'A tiny crochet bloom planted in a mini pot — a little piece of permanent garden.',
  'The Mini Flower Pot is a crochet flower set in a small decorative pot. It is a complete little piece of decor — a permanent garden for a desk, a shelf, or a windowsill.',
  15,
  true,
  true,
  false,
  false,
  true,
  '3–5 days',
  '',
  ARRAY['https://images.pexels.com/photos/17864123/pexels-photo-17864123.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/32280850/pexels-photo-32280850.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Pink', 'White', 'Yellow', 'Custom']::text[],
  ARRAY['Housewarming', 'Just Because', 'Mother''s Day']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BG-001',
  'Mini Crochet Purse',
  'tpb-bg-001',
  'bags',
  54900,
  null,
  'A small, charming crochet purse for everyday essentials.',
  'The Mini Crochet Purse is a compact, handmade bag with a soft textured finish. It is the kind of piece that adds a handmade touch to an everyday outfit.',
  15,
  true,
  true,
  false,
  false,
  true,
  '4–6 days',
  '',
  ARRAY['https://images.pexels.com/photos/33207480/pexels-photo-33207480.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/30224898/pexels-photo-30224898.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Cream', 'Pink', 'Sage', 'Brown', 'Custom']::text[],
  ARRAY['Birthday', 'Just Because']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BG-002',
  'Petal Tote',
  'tpb-bg-002',
  'bags',
  89900,
  null,
  'A medium crochet tote with floral accents — functional and beautiful.',
  'The Petal Tote is a medium-sized crochet bag with delicate floral accents woven into the design. It is roomy enough for daily use and pretty enough to carry with intention.',
  15,
  true,
  true,
  false,
  false,
  true,
  '5–7 days',
  '',
  ARRAY['https://images.pexels.com/photos/30224898/pexels-photo-30224898.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/30859913/pexels-photo-30859913.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Cream', 'Sage', 'Brown', 'Custom']::text[],
  ARRAY['Birthday', 'Just Because']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-BG-003',
  'Premium Tote',
  'tpb-bg-003',
  'bags',
  129900,
  null,
  'A large, fully-lined crochet tote with a premium finish and sturdy straps.',
  'The Premium Tote is our finest bag — a large, fully-lined crochet tote with sturdy straps and a structured finish. It is made to be used, carried, and loved for years.',
  15,
  true,
  true,
  false,
  true,
  true,
  '5–7 days',
  '',
  ARRAY['https://images.pexels.com/photos/30859913/pexels-photo-30859913.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/30224897/pexels-photo-30224897.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Cream', 'Brown', 'Sage', 'Custom']::text[],
  ARRAY['Birthday', 'Anniversary']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-GF-001',
  'Little Bloom Gift Box',
  'tpb-gf-001',
  'giftboxes',
  79900,
  null,
  'A single crochet bloom, a keyring, and a greeting card in a gift-ready box.',
  'The Little Bloom Gift Box brings together a single crochet flower, a Pocket Bloom keyring, and a greeting card in a beautifully packaged box. It is a complete gift — ready to give, ready to receive.',
  15,
  true,
  true,
  false,
  true,
  true,
  '4–6 days',
  '',
  ARRAY['https://images.pexels.com/photos/10482144/pexels-photo-10482144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/13143524/pexels-photo-13143524.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Custom mix available']::text[],
  ARRAY['Birthday', 'Friendship', 'Just Because', 'Mother''s Day']::text[],
  ARRAY[]::text[],
  ARRAY['1 crochet flower', 'Pocket Bloom keyring', 'Greeting card', 'Gift box packaging']::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-GF-002',
  'Premium Bloom Box',
  'tpb-gf-002',
  'giftboxes',
  149900,
  null,
  'A trio of crochet blooms, a keyring, a bookmark, and a greeting card in a premium box.',
  'The Premium Bloom Box is our most complete gift — a Trio of Petals bouquet, a Pocket Bloom keyring, a Flower Bookmark, and a greeting card, all presented in a premium gift box with wrapping and ribbon. It is the gift that needs nothing else.',
  15,
  true,
  true,
  false,
  false,
  true,
  '5–7 days',
  '',
  ARRAY['https://images.pexels.com/photos/27291954/pexels-photo-27291954.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/13143524/pexels-photo-13143524.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Custom mix available']::text[],
  ARRAY['Anniversary', 'Mother''s Day', 'Birthday', 'Valentine''s Day']::text[],
  ARRAY[]::text[],
  ARRAY['Trio of Petals bouquet (3 flowers)', 'Pocket Bloom keyring', 'Flower bookmark', 'Greeting card', 'Premium gift box with wrapping and ribbon']::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;

insert into public.products (
  code,
  name,
  slug,
  category_slug,
  price_in_paise,
  compare_at_price_in_paise,
  description,
  long_description,
  inventory_count,
  is_made_to_order,
  is_customisable,
  is_bestseller,
  is_featured,
  is_active,
  preparation_days,
  bouquet_size,
  images,
  colors,
  occasions,
  recipients,
  whats_included
) values (
  'TPB-CS-001',
  'Custom Bouquet',
  'tpb-cs-001',
  'custom',
  119900,
  null,
  'Your flowers. Your colours. Your story — a bouquet designed entirely around you.',
  'The Custom Bouquet is our made-to-order experience. You choose the flower types, the number of flowers, the colours, the wrapping, the ribbon, and the message. We handcraft it from scratch. No two custom bouquets are the same.',
  15,
  true,
  true,
  false,
  true,
  true,
  '5–10 days',
  'Your choice',
  ARRAY['https://images.pexels.com/photos/29753249/pexels-photo-29753249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'https://images.pexels.com/photos/20269075/pexels-photo-20269075.jpeg?auto=compress&cs=tinysrgb&h=650&w=940']::text[],
  ARRAY['Fully custom']::text[],
  ARRAY['All occasions']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[]
)
on conflict (code) do update set
  name = excluded.name,
  category_slug = excluded.category_slug,
  price_in_paise = excluded.price_in_paise,
  description = excluded.description,
  images = excluded.images;
